### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by MustafaHussaini** [stimulsoft/Samples-JS#13]
How can we use library with vue?

I import library like this and it returns undefined for stumlisoft.
`import stimulsoft from './lib/stimulsoft.reports.maps.js'

 export default {
        methods: {
            print() {
                let report = new Stimulsoft.Report.StiReport();
                console.log(report ); `

error message: "TypeError: Cannot read property 'StiReport' of undefined"

**Comment by AntonLozovskiy** [comment]
Hello, Mustafa,

Here is a sample for Vue.js
https://github.com/stimulsoft/Samples-JS/tree/master/Vue.js

**Comment by MustafaHussaini** [comment]
Hello, AntonLozovskiy,
thank you very much for vue sample.

**Comment by MustafaHussaini** [comment]
Hello, AntonLozovskiy,
thank you very much for vue sample.
