### ISSUE TITLE
Text over image , preview not working

### ISSUE THREAD

**Issue by basilinjoe** [stimulsoft/Samples-JS#2]
When i insert text over an image in designer , preview breaks .. but when i download report everything is working fine .. on angular example

**Comment by AntonLozovskiy** [comment]
Hello,

Thank you for the question.
Here are two solutions:
var options = new Stimulsoft.Designer.StiDesignerOptions();
options.appearance.htmlRenderMode = Stimulsoft.Report.Export.StiHtmlExportMode.Div;

or
var options = new Stimulsoft.Designer.StiViewerOptions();
options.appearance.htmlRenderMode = Stimulsoft.Report.Export.StiHtmlExportMode.Div;

Thank you.
