### ISSUE TITLE
Pdf Export not working when report contains linked images

### ISSUE THREAD

**Issue by basilinjoe** [stimulsoft/Samples-JS#3]
When i import image from url and preview works fine but when i am trying to export it to pdf am getting an error .. 
![image001](https://cloud.githubusercontent.com/assets/11013326/15045004/b62afb60-12f5-11e6-8357-7229ed7454c0.png)

**Comment by AntonLozovskiy** [comment]
Thank you for the bug report. We will check this.

**Comment by kubekin2** [comment]
For exporting image need to download image as data.
Browser does not do this from another domain.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)
