### ISSUE TITLE
Hello Exporting Report to pdf

### ISSUE THREAD

**Issue by GuillermoParedes** [stimulsoft/Samples-JS#4]
Hello, when I'm exporting the report to PDF, obtain the report in byte [], I can keep it, but does not show me the image that is in the report.

**Comment by HighAley** [comment]
Could you specify which version of our scripts you use?

**Comment by kubekin2** [comment]
For exporting image need to download image as data.
Browser does not do this from another domain.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)
