### ISSUE TITLE
Any way around this? Uncaught TypeError: Cannot read property 'Localization' of undefined

### ISSUE THREAD

**Issue by teilin** [stimulsoft/Samples-JS#5]
Hi, I am checking out StimulsoftJS if it is suitable for a project. I am going to use Angular2. I have been able to require the javascript files, but when testing in chrome it is giving me an error message like:

```
Uncaught TypeError: Cannot read property 'Localization' of undefined
    at e.Viewer.e.Viewer (stimulsoft.viewer.js:20)
    at Stimulsoft (stimulsoft.viewer.js:20)
    at stimulsoft.viewer.js:20
e.Viewer.e.Viewer @ stimulsoft.viewer.js:20
Stimulsoft @ stimulsoft.viewer.js:20
(anonymous) @ stimulsoft.viewer.js:20
```

Is it any way to get around this and use the StimulsoftJS in an Angular2 project?

**Comment by dsjh** [comment]
Hi teilin, did you ever resolve this issue I am facing exactly the same error now

**Comment by teilin** [comment]
No, I did not. Actually I had a tight schedule so did not have to much time to see if I could find a solution. What I ended up using since I already was going to use asp.net core is this  https://www.nuget.org/packages/Stimulsoft.Reports.NetCore/2017.1.0-rc6 

They have a great collection of samples here: https://github.com/stimulsoft/Samples-NET.Core-CSharp

**Comment by dsjh** [comment]
Thanks, I have an Asp.net license for stimulsoft, I just wanted to use Angular to avoid compilation delays.

**Comment by kubekin2** [comment]
Please check it [https://github.com/stimulsoft/Samples-JS/tree/master/Angular2](https://github.com/stimulsoft/Samples-JS/tree/master/Angular2)

**Comment by HASSANDL** [comment]
hello, I same this error in angular 1.6.
please help me.
```
Uncaught TypeError: Cannot read property 'Localization' of undefined
at e.Viewer.e.Viewer (stimulsoft.viewer.js:20)
at Stimulsoft (stimulsoft.viewer.js:20)
at stimulsoft.viewer.js:20
```
this error show even only load below files without use report.
```
<script src="scripts/stimulsoft.reports.js" type="text/javascript"></script>
<script src="scripts/stimulsoft.viewer.js" type="text/javascript"></script>
```

**Comment by dsjh** [comment]
@HASSANDL did you resolve this? I still have not.

What node packages are you using? I am using a aspnetzero template which uses many packages so I'm unsure which might be causing the conflict.

**Comment by kubekin2** [comment]
Can I close this issue?

**Comment by dsjh** [comment]
I resolved my issue by removing moment.timezone package, that was being called via moment.tz.setDefault(abp.timing.timeZoneInfo.iana.timeZoneId);
