### ISSUE TITLE
exporting pdf contains image issue

### ISSUE THREAD

**Issue by linkstops** [stimulsoft/Samples-JS#6]
hallo,
my problem is when i get the exported report  from the server (node js) in format (pdf,xls,doc) the pdf i get in my email doesnt contains images but it works perfect with xls and doc . if there is any help to make stimule soft  encode images when exported to pdf in the server side and i tried all type of images but still not solved it doest show images on exported pdf files sent to my email 

thanks

**Comment by kubekin2** [comment]
For exporting image need to download image as data.
Browser does not do this from another domain.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)
