### ISSUE TITLE
angular2

### ISSUE THREAD

**Issue by yeganehaym** [stimulsoft/Samples-JS#7]
hi
what about angular 2 sample?

**Comment by dsjh** [comment]
Yes, please provide angular 2 example.

**Comment by kritisoft** [comment]
Any Update with the Angular 2 Samples ?

**Comment by yeganehaym** [comment]
i guess there is not any support of stimulsoft anymore

**Comment by kubekin2** [comment]
Please check it https://github.com/stimulsoft/Samples-JS/tree/master/Angular2[https://github.com/stimulsoft/Samples-JS/tree/master/Angular2](url)
